"发行日期" = "2026-08-09"
"出品" = ["电鱼"]
"前缀" = ""
"中文名" = "碎屑"
"英文名" = ""
"后缀" = ""
"歌词制作" = ["神武竹"]
"发布" = "[Bilibili](https://www.bilibili.com/video/BV1r54y1i7yj)"
"购买" = ""
"电子" = ""
"演唱" = ["星尘", "海伊"]
"作词" = ["电鱼"]
"作曲" = ["电鱼"]
"编曲" = ["电鱼", "靘"]
"调校" = ["电鱼", "观默"]
"曲绘" = ["电鱼"]
"混音" = ["电鱼", "靘", "46_P"]
"母带" = []
"视频" = []
"策划" = []
