<template>
  <aside class="workspace-explorer" aria-label="工作区文件资源管理器" :inert="busy || undefined">
    <div class="workspace-explorer-head"><strong>资源管理器</strong><button type="button" aria-label="刷新工作区" @click="$emit('refresh')">↻</button></div>
    <section class="workspace-group"><div class="workspace-group-head"><button type="button" :aria-expanded="draftOpen" @click="draftOpen = !draftOpen"><span>{{ draftOpen ? '⌄' : '›' }}</span> 草稿</button><button type="button" aria-label="新建专辑" title="新建专辑" @click="$emit('create-album')">＋</button></div><template v-if="draftOpen"><p v-if="!drafts.length && !pending.length" class="workspace-tree-empty">暂无草稿</p><div v-for="entry in drafts" :key="entry.key" class="workspace-album"><div class="workspace-root"><button type="button" :aria-expanded="expanded.includes(entry.key)" @click="$emit('toggle', entry.key)"><span>{{ expanded.includes(entry.key) ? '⌄' : '›' }}</span><span class="workspace-tree-label">{{ entry.label }}<small v-if="entry.owner" class="workspace-owner">@{{ entry.owner }}</small></span><span v-if="entry.dirty" aria-label="专辑未保存">●</span></button><template v-if="writable(entry)"><label :aria-label="`上传素材 ${entry.label}`" title="上传素材" class="workspace-upload-action">↑<input type="file" multiple @change="upload($event, entry.key, '')"></label><button type="button" :aria-label="`新建文件 ${entry.label}`" @click="startCreate(entry.key, 'file', '')">＋</button><button type="button" :aria-label="`新建文件夹 ${entry.label}`" @click="startCreate(entry.key, 'folder', '')">□</button></template><button type="button" :aria-label="`丢弃草稿 ${entry.label}`" @click="$emit('discard-draft', entry.key)">×</button></div><form v-if="creating?.key === entry.key && !creating.parentPath" class="workspace-tree-create" @submit.prevent="submitCreate"><input ref="rootInput" v-model="creating.name" :aria-label="creating.kind === 'folder' ? '新建文件夹名称' : '新建文件名称'" :disabled="busy" @keydown.esc.prevent="creating = null"><button type="submit" :disabled="busy || !creating.name.trim()">创建</button><p v-if="creating.error" role="alert">{{ creating.error }}</p></form><div v-if="expanded.includes(entry.key)" class="workspace-tree"><WorkspaceTreeNode v-for="node in entry.nodes[0]?.children" :key="node.id" :node="node" :selected-id="selectedId" :editable="writable(entry)" :creating="creating?.key === entry.key ? creating : null" :busy="busy" @open="$emit('open', $event, entry.key)" @start-create="value => startCreate(entry.key, value.kind, value.parentPath)" @submit-create="submitCreate" @cancel-create="creating = null" @upload="value => $emit('upload', { key: entry.key, ...value })" /></div></div><article v-for="item in pending" :key="item.ref + item.storage_album" class="workspace-pending"><button type="button" :disabled="processing(item) || failed(item)" @click="$emit('open-pending', item)"><strong>{{ item.album }}</strong><small>{{ item.message || stateLabel(item) }}</small></button><span><button v-if="failed(item)" type="button" @click="$emit('retry', item)">重试</button><button type="button" @click="$emit('discard', item)">丢弃</button></span></article></template></section>
    <section class="workspace-group"><div class="workspace-group-head"><button type="button" :aria-expanded="catalogOpen" @click="catalogOpen = !catalogOpen"><span>{{ catalogOpen ? '⌄' : '›' }}</span> 成品修改</button></div><template v-if="catalogOpen"><div v-for="item in catalog" :key="item.slug" class="workspace-album"><template v-if="item.workspace"><div class="workspace-root"><button type="button" :aria-expanded="expanded.includes(item.workspace.key)" @click="$emit('toggle', item.workspace.key)"><span>{{ expanded.includes(item.workspace.key) ? '⌄' : '›' }}</span><span class="workspace-tree-label">{{ item.workspace.label }}</span><span v-if="item.workspace.dirty" aria-label="专辑未保存">●</span></button><template v-if="writable(item.workspace)"><label :aria-label="`上传素材 ${item.workspace.label}`" class="workspace-upload-action">↑<input type="file" multiple @change="upload($event, item.workspace.key, '')"></label><button type="button" :aria-label="`新建文件 ${item.workspace.label}`" @click="startCreate(item.workspace.key, 'file', '')">＋</button><button type="button" :aria-label="`新建文件夹 ${item.workspace.label}`" @click="startCreate(item.workspace.key, 'folder', '')">□</button></template></div><form v-if="creating?.key === item.workspace.key && !creating.parentPath" class="workspace-tree-create" @submit.prevent="submitCreate"><input ref="rootInput" v-model="creating.name" :aria-label="creating.kind === 'folder' ? '新建文件夹名称' : '新建文件名称'" :disabled="busy" @keydown.esc.prevent="creating = null"><button type="submit" :disabled="busy || !creating.name.trim()">创建</button><p v-if="creating.error" role="alert">{{ creating.error }}</p></form><div v-if="expanded.includes(item.workspace.key)" class="workspace-tree"><WorkspaceTreeNode v-for="node in item.workspace.nodes[0]?.children" :key="node.id" :node="node" :selected-id="selectedId" :editable="writable(item.workspace)" :creating="creating?.key === item.workspace.key ? creating : null" :busy="busy" @open="$emit('open', $event, item.workspace.key)" @start-create="value => startCreate(item.workspace.key, value.kind, value.parentPath)" @submit-create="submitCreate" @cancel-create="creating = null" @upload="value => $emit('upload', { key: item.workspace.key, ...value })" /></div></template><button v-else class="workspace-catalog" type="button" @click="$emit('open-catalog', item)"><span>◇</span>{{ item.name || item.folder || item.slug }}</button></div><p v-if="!catalog.length" class="workspace-tree-empty">暂无成品</p></template></section>
  </aside>
</template>
<script setup>
import { nextTick, ref, watch } from 'vue';
import WorkspaceTreeNode from './WorkspaceTreeNode.vue';
const props = defineProps({ drafts: { type: Array, default: () => [] }, pending: { type: Array, default: () => [] }, catalog: { type: Array, default: () => [] }, expanded: { type: Array, default: () => [] }, selectedId: String, busy: Boolean, creationFeedback: { type: Object, default: () => ({}) } });
const emit = defineEmits(['refresh', 'create-album', 'create-document', 'upload', 'toggle', 'open', 'open-pending', 'retry', 'discard', 'discard-draft', 'open-catalog']);
const draftOpen = ref(true); const catalogOpen = ref(true); const creating = ref(null); const rootInput = ref(null);
const writable = entry => entry?.origin === 'workspace' && !entry.readOnly;
function startCreate(key, kind, parentPath) { if (!props.busy) creating.value = { key, kind, parentPath, name: '', error: '' }; }
function submitCreate() { if (!creating.value?.name.trim() || props.busy) return; creating.value.error = ''; emit('create-document', { ...creating.value, name: creating.value.name.trim() }); }
function upload(event, key, parentPath) { const files = Array.from(event.target.files || []); event.target.value = ''; if (files.length) emit('upload', { key, files, parentPath }); }
watch(() => creating.value && !creating.value.parentPath, async active => { if (active) { await nextTick(); (Array.isArray(rootInput.value) ? rootInput.value[0] : rootInput.value)?.focus(); } });
watch(() => props.creationFeedback.sequence, () => { const feedback = props.creationFeedback; if (!creating.value || feedback.key !== creating.value.key) return; if (feedback.ok) creating.value = null; else creating.value.error = feedback.error || '创建失败'; });
const failed = item => item?.state === 'failed' || item?.status === 'failed'; const processing = item => ['queued', 'dispatching', 'running', 'processing', 'submitted', 'job_started'].includes(item?.state) || item?.status === 'processing'; const stateLabel = item => failed(item) ? '处理失败' : processing(item) ? '处理中' : item?.state === 'done' ? '已完成' : '待审核';
</script>
